import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import JoyStick from '../../public/joystick.png'
import {
    ButtonAction,
    ButtonDetails,
    ImageBackground,
    Item,
    Logo,
    Main,
    Menu,
    Nav,
    Tag,
    Text,
    Title
} from '../styles'

export default function Home () {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Nav>
          <Logo>
            <strong>LOGO</strong>
          </Logo>
          <Menu>
            <Item href="#">Home</Item>
            <Item href="#">About Us</Item>
            <Item href="#">Portfolio</Item>
            <Item href="#">News</Item>
            <ButtonAction>Contact Us</ButtonAction>
          </Menu>
        </Nav>

        <Main>
            <Tag>3D game Dev</Tag>
            <Title>Work that we <br/> produce for our<br/> clients</Title>
            <Text>
            Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
            </Text>
            <ButtonDetails>
                Get more details
            </ButtonDetails>
        </Main>
        <ImageBackground>
            <Image
                src={JoyStick}
                alt="Joy Stick"
            />
        </ImageBackground>
      </header>
    </div>
  )
}
